spring:
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        max-connections: 200
        max-connections-per-route: 200
#spring:
#  cloud:
#    openfeign:
#      httpclient:
#        enabled: true
#        max-connections: 200
#        max-connections-per-route: 200